name: Rulesetes protection

on:
  workflow_dispatch:

jobs:
  Branch-Protection:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - id: read-json-rules
        run: echo "RULESETS=$(jq -c . < ./rulesets.json)" >> $GITHUB_OUTPUT

      - id: read-json-repos
        run: echo "REPOSITORIES=$(jq -c . < ./repositories.json)" >> $GITHUB_OUTPUT

      - name: Set protection rules on selected reposiories
        run: |
          repo_names=$(jq -r '.repositories[].repo_name' repositories.json) && echo $repo_names
          owner=$(jq -r '.owner' repositories.json) && echo $owner

          for u in $repo_names
          do
          curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GH_PAT }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/$owner/$u/rulesets \
          -d '{"name":"super cool ruleset","target":"branch","enforcement":"active","bypass_actors":[{"actor_id":234,"actor_type":"Team","bypass_mode":"always"}],"conditions":{"ref_name":{"include":["refs/heads/main","refs/heads/master"],"exclude":["refs/heads/dev*"]}}}'
          done