 
        run: |
          # LISTAR REPOS
          REPOS="Test.Microservice.2 Test.Microservice.1 Test.Microfrontend.2 Test.Microfrontend.1"
          
          # LOOP DE REPOS
          for u in $REPOS
          do
            echo $u
            # CARGAR LAS BRANCHES EN UN TXT
            curl -L -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.GH_PAT }}" -H "X-GitHub-Api-Version: 2022-11-28" "https://api.github.com/repos/CleverSandbox/$u/branches" | jq -r '.[].name' > BRANCHES.txt
            # CARGAR SI LAS BRANCHES ESTAN PROTEGIDAS EN UN TXT
            curl -L -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.GH_PAT }}" -H "X-GitHub-Api-Version: 2022-11-28" "https://api.github.com/repos/CleverSandbox/$u/branches" | jq -r '.[].protected' > IS_PROTECTED.txt
            # VARIABLE DEFAULT BRANCH (SE LE CONFIGURA PROTECTED BRANCH POR DEFAULT) - NOMBRE DE DEFAULT BRANCH
            export DEFAULT_BRANCH=$(curl -L -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.GH_PAT }}" -H "X-GitHub-Api-Version: 2022-11-28" "https://api.github.com/repos/CleverSandbox/$u" | jq -r '.default_branch')
            # VARIABLE NUMERO DE BRANCHES
            export NUMBER_OF_BRANCHES=$(awk 'END {print NR}' BRANCHES.txt)
            # LOOP QUE ITERA POR TODAS LAS BRANCHES
            
            for i in $(seq 1 $NUMBER_OF_BRANCHES)
            do
              # CONDICIONAL - SI LA BRANCH ESTA PROTEGIDA
              if [[ $(awk -v i=$i 'NR==i' IS_PROTECTED.txt) == true ]]
              then
                # EXPORTAR NOMBRE DE LA BRANCH PROTEGIDA
                export BRANCH=$(awk -v i=$i 'NR==i' BRANCHES.txt)
                # CONFIGURAR LA PROTECCION DESEADA
                curl -L -X PUT -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.GH_PAT }}" -H "X-GitHub-Api-Version: 2022-11-28" "https://api.github.com/repos/CleverSandbox/$u/branches/$BRANCH/protection" -d '${{ steps.read-json-config.outputs.BRANCH_CONFIGURATION }}'
              fi
            done
          # SE LE CONFIGURA LA PROTECCION DESEADA A LA DEFAULT BRANCH FUERA DEL BUCLE (YA QUE HAY SITUACIONES EN EL QUE LA DEFAULT BRANCH NO ESTA PROTEGIDA Y EL LOOP LO VA A OMITIR
          curl -L -X PUT -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.GH_PAT }}" -H "X-GitHub-Api-Version: 2022-11-28" "https://api.github.com/repos/CleverSandbox/$u/branches/$BRANCH/protection" -d '${{ steps.read-json-config.outputs.BRANCH_CONFIGURATION }}'
          # SE ELIMINAN LOS ARCHIVOS TXT GENERADOS
          rm BRANCHES.txt IS_PROTECTED.txt
          
          done